// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC24j1mcukDV6rBdFJrZguSWL4vu5YKg6Q',
    appId: '1:312634462857:web:c13807415155c88a4c6c58',
    messagingSenderId: '312634462857',
    projectId: 'biye-49f1f',
    authDomain: 'biye-49f1f.firebaseapp.com',
    storageBucket: 'biye-49f1f.firebasestorage.app',
    measurementId: 'G-H28BG56EYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc90IKMUTtVWiTivQ8caX1PU82XG--Zmw',
    appId: '1:312634462857:android:ae0f0012246c9cd74c6c58',
    messagingSenderId: '312634462857',
    projectId: 'biye-49f1f',
    storageBucket: 'biye-49f1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_rfDp7vPncVrDg7Aj6wwgoY2pADq5CkQ',
    appId: '1:312634462857:ios:9159e766fa7dfcb04c6c58',
    messagingSenderId: '312634462857',
    projectId: 'biye-49f1f',
    storageBucket: 'biye-49f1f.firebasestorage.app',
    iosBundleId: 'com.example.biye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_rfDp7vPncVrDg7Aj6wwgoY2pADq5CkQ',
    appId: '1:312634462857:ios:9159e766fa7dfcb04c6c58',
    messagingSenderId: '312634462857',
    projectId: 'biye-49f1f',
    storageBucket: 'biye-49f1f.firebasestorage.app',
    iosBundleId: 'com.example.biye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC24j1mcukDV6rBdFJrZguSWL4vu5YKg6Q',
    appId: '1:312634462857:web:d6571ba15411f0054c6c58',
    messagingSenderId: '312634462857',
    projectId: 'biye-49f1f',
    authDomain: 'biye-49f1f.firebaseapp.com',
    storageBucket: 'biye-49f1f.firebasestorage.app',
    measurementId: 'G-5ENSNG72GV',
  );
}
